import {create} from 'zustand'
const useRegisterStore=create((set)=>({
    firstName: "",
    lastName: "",
    email: "",
    phoneNumber: "",
    resumeFile: null,
    password:'',
    portfolioUrl: "",
    referral: "",
    jobMail: true,
    profilePicFile: null,
    countryCode: "",
    jobRoles: ["Instructional Designer", "Software Engineer","Software Quality Engineer"],
    setFirstName: (value) => set({ firstName: value }),
    setLastName: (value) => set({ lastName: value }),
    setEmail: (value) => set({ email: value }),
    setPassword: (value) => set({ password: value }),
    setPhoneNumber: (value) => set({ phoneNumber: value }),
    setResumeFile: (value) => set({ resumeFile: value }),
    setPortfolioUrl: (value) => set({ portfolioUrl: value }),
    setReferral: (value) => set({ referral: value }),
    setJobMail: (value) => set({ jobMail: value }),
    setProfilePicFile: (value) => set({ profilePicFile: value }),
    setCountryCode: (value) => set({ countryCode: value }),
    setJobRoles: (value) => set({ jobRoles: value }),
}))
export default useRegisterStore;